---
name: Sonarr
version: 4.0.19.3009
slug: sonarr
description: Smart PVR for newsgroup and bittorrent users
url: https://github.com/hassio-addons/app-sonarr/tree/main/README.md
webui: http://[HOST]:[PORT:8989]
init: false
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8989/tcp: 8989
