---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

jobs:
  ci:
    permissions:
      actions: read
      contents: write
      pull-requests: read
      packages: read
      security-events: write
    uses: ./.github/workflows/app-ci.yaml

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/app-deploy.yaml
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
